version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile-app
    image: django-server:latest
    stdin_open: true
    tty: true 
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
  
  tailwind:
    build:
      context: ./
      dockerfile: Dockerfile-app
    image: tailwind-server:latest
    command: python manage.py tailwind start
    volumes:
      - ./app:/usr/src/app
    tty: true
    environment:
    - POSTGRES_NAME=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - web
      - db

volumes:
  db-data: