FROM python:3.13.0a4-alpine3.19

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apk update && apk add --no-cache postgresql-dev gcc python3-dev musl-dev
#todo: check if i can remove python3-dev musl-dev without breaking tailwind

COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# DEV only Packages: Nodejs/npm is needed for tailwind in dev. make is for comfort :)
RUN apk add --no-cache nodejs npm make

COPY ./app .

#todo: check if it still works with a non root user. Uncomment next section

# Create a non-root user and switch to it
#RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Change ownership of the working directory to the non-root user
#RUN chown -R appuser:appgroup /usr/src/app

# Switch to the non-root user
#USER appuser

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
