FROM python:3.13.0a4-alpine3.19

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# ENV DJANGO_SETTINGS_MODULE=myproject.settings_prod

WORKDIR /usr/src/app

RUN apk update && apk add --no-cache postgresql-dev gcc python3-dev musl-dev

COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app .

# Create a non-root user and switch to it
#RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Change ownership of the working directory to the non-root user
#RUN chown -R appuser:appgroup /usr/src/app

# Switch to the non-root user
#USER appuser

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
